---
slug: database_book
filename: database_book
title: Title of the Book
subtitle: Change me
description: Change me.
author: Author Name
copyright: 2017
uuid: 23a8d0ff-9db0-42c7-a1f3-398ad6b22c87
pdf_preview_page_range: 1..30
epub_mobi_preview_chapter_range: 0..1
