---
slug: database_book
filename: database_book
title: Database Management System
subtitle: or what I hate
description: I'm reading and reading this book but I'm failed and can't pass it. I don't know what to do to pass this course but I know I can provide my knowledge to other. It is good to help people when you can, my teacher.
author: by Mischievous Naughty Child
copyright: 2017
uuid: 23a8d0ff-9db0-42c7-a1f3-398ad6b22c87
pdf_preview_page_range: 1..30
epub_mobi_preview_chapter_range: 0..1
